"""empty message

Revision ID: 724efbe61f8c
Revises: e39603e778ed
Create Date: 2023-06-01 02:19:05.982067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724efbe61f8c'
down_revision = 'e39603e778ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
