"""empty message

Revision ID: 75acb6ae3c48
Revises: 3794a550b313
Create Date: 2023-05-30 19:47:27.749804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75acb6ae3c48'
down_revision = '3794a550b313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
